### ISSUE TITLE
Two errors while doing timewalking raid.

### ISSUE THREAD

**Issue by KurtzPT** [BoxximusPrime/WhoGotLoots#4]
```
1x WhoGotLoots/WhoGotLoots.lua:199: attempt to concatenate local 'slotName' (a nil value)
[string "@WhoGotLoots/WhoGotLoots.lua"]:199: in function <WhoGotLoots/WhoGotLoots.lua:165>
[string "=[C]"]: in function `xpcall'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:76: in function `FireCallbacks'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:35: in function <.../Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua:31>
[string "=[C]"]: ?
[string "=[C]"]: in function `accessor'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:52: in function `AddCallback'
[string "@Blizzard_ObjectAPI/Mainline/Item.lua"]:332: in function `ContinueOnItemLoad'
[string "@WhoGotLoots/WhoGotLoots.lua"]:165: in function `AddLootFrame'
[string "@WhoGotLoots/WhoGotLoots.lua"]:55: in function <WhoGotLoots/WhoGotLoots.lua:22>

Locals:
CompareItemID = 150770
CompareItemIlvl = 597
isPreview = false
baseIlvl = 33
itemName = "Jerkin of the Broken Sage"
linkedItem = "|cffa335ee|Hitem:150770::::::::80:105::54:5:10273:10377:7756:10031:10255:1:28:2462:::::|h[Jerkin of the Broken Sage]|h|r"
itemQuality = 4
itemLevel = 597
itemMinLevel = 80
itemType = "Armor"
itemSubType = "Leather"
itemStackCount = 1
itemEquipLoc = "INVTYPE_ROBE"
itemTexture = 609748
sellPrice = 955992
classID = 4
subclassID = 2
bindType = 1
expansionID = 1
setID = nil
isCraftingReagent = false
PlayerTopStat = "Intellect"
BottomText = <table> {
}
BottomText2 = <table> {
}
CanEquip = true
IsAppropriate = true
ItemHasMainStat = true
slotName = nil
(*temporary) = "Slot Name: "
(*temporary) = nil
(*temporary) = nil
(*temporary) = false
(*temporary) = nil
(*temporary) = 597
(*temporary) = 80
(*temporary) = "Armor"
(*temporary) = "Leather"
(*temporary) = 1
(*temporary) = "INVTYPE_ROBE"
(*temporary) = 609748
(*temporary) = 955992
(*temporary) = 4
(*temporary) = 2
(*temporary) = 1
(*temporary) = 1
(*temporary) = nil
(*temporary) = false
(*temporary) = false
(*temporary) = nil
(*temporary) = false
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'slotName' (a nil value)"
itemLink = "|cffa335ee|Hitem:150770::::::::80:105::54:5:10273:10377:7756:10031:10255:1:28:2462:::::|h[Jerkin of the Broken Sage]|h|r"
player = "Chromia"
```

```
1x WhoGotLoots/WhoGotLoots.lua:200: Invalid inventory slot in GetInventorySlotInfo
[string "=[C]"]: in function `GetInventorySlotInfo'
[string "@WhoGotLoots/WhoGotLoots.lua"]:200: in function <WhoGotLoots/WhoGotLoots.lua:165>
[string "=[C]"]: in function `xpcall'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:76: in function `FireCallbacks'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:35: in function <.../Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua:31>
[string "=[C]"]: ?
[string "=[C]"]: in function `accessor'
[string "@Blizzard_ObjectAPI/Mainline/AsyncCallbackSystem.lua"]:52: in function `AddCallback'
[string "@Blizzard_ObjectAPI/Mainline/Item.lua"]:332: in function `ContinueOnItemLoad'
[string "@WhoGotLoots/WhoGotLoots.lua"]:165: in function `AddLootFrame'
[string "@WhoGotLoots/WhoGotLoots.lua"]:55: in function <WhoGotLoots/WhoGotLoots.lua:22>

Locals:
(*temporary) = "RangedSlot"
```

**Comment by BoxximusPrime** [comment]
I also did the TWW raid last night, and had the same error as the first one which I believe I have fixed. The 2nd error I'm not sure, though, do you remember the item name, or at least what item it was that dropped?

**Comment by KurtzPT** [comment]
> I also did the TWW raid last night, and had the same error as the first one which I believe I have fixed. The 2nd error I'm not sure, though, do you remember the item name, or at least what item it was that dropped?

I don't remember, I noticed the two errors on the bucksack addon after the raid ended.

**Comment by KurtzPT** [comment]
@BoxximusPrime in case you didn't fix yet the 2nd error, I got it again in the BT raid.
These were the items that dropped:

![image](https://github.com/user-attachments/assets/e31893f2-bc44-4486-965d-366ca8d52de5)

I'm assuming the loot that gave the error was the Wand: Naaru-Blessed Life Rod
